name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Lunarg repo
      run: echo "deb https://packages.lunarg.com/vulkan focal main" | sudo tee /etc/apt/sources.list.d/lunarg-vulkan-focal.list
    - name: Lunarg key
      run: wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
    - name: apt-get update
      run: sudo apt-get update
    - name: Install packages
      run: sudo apt-get install vulkan-tools glslang-dev mesa-vulkan-drivers libvulkan-dev vulkan-headers libopenblas-openmp-dev libcmocka-dev libplplot-dev libnetcdf-dev cmake ninja-build
    - name: configure
      run: mkdir build && cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - name: make
      run: cmake --build build
    - name: vulkaninfo
      run: vulkaninfo --summary
    - name: test
      run: cmake --build build --target test
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.28
      if: always()
      with:
         files: build/ut/*.xml
